package Modelo;
// Generated 28-jul-2020 23:09:37 by Hibernate Tools 4.3.1



/**
 * Promocion generated by hbm2java
 */
public class Promocion  implements java.io.Serializable {


     private Integer idPromocion;
     private String codigo;
     private int descuento;

    public Promocion() {
    }

    public Promocion(String codigo, int descuento) {
       this.codigo = codigo;
       this.descuento = descuento;
    }
   
    public Integer getIdPromocion() {
        return this.idPromocion;
    }
    
    public void setIdPromocion(Integer idPromocion) {
        this.idPromocion = idPromocion;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public int getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(int descuento) {
        this.descuento = descuento;
    }




}


